- name: Install WordPress
  hosts: localhost
  become: yes
  vars:
    wordpress_version: "{{ WPV }}"
    db_name: "{{ DBNAME }}"
    db_user: "{{ USERNAME }}"
    db_password: "{{ PASSWORD }}"
    db_host: "{{ ENDPOINT }}"
    db_prefix: "wp_"
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Debug WordPress variables
      debug:
        var: 
          wordpress_version: "{{ wordpress_version }}"
          db_name: "{{ db_name }}"
          db_user: "{{ db_user }}"
          db_password: "{{ db_password }}"
          db_host: "{{ db_host }}"
          db_prefix: "{{ db_prefix }}"

    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - curl
        state: present

    - name: Download and extract WordPress
      get_url:
        url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set ownership and permissions
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        recurse: yes

    - name: Create wp-config.php
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
      when: not ansible_check_mode

    - name: Configure Apache for WordPress
      become: yes
      become_method: sudo
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf 
        state: present
      when: not ansible_check_mode

  handlers:
    - name: Restart Apache
      become: yes
      become_method: sudo
      service:
        name: apache2
        state: restarted
