---
- name: Install WordPress
  hosts: localhost
  become: yes
  vars:
    wordpress_version: "{{ WPV }}"
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - curl
        state: present

    - name: Download and extract WordPress
      get_url:
        url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set ownership and permissions
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        recurse: yes

    - name: Configure WordPress database
      command: >
        wp core config
        --dbname=wordpress
        --dbuser=root
        --dbpass=your_password
        --dbhost=localhost
        --dbprefix=wp_
        --path=/var/www/html/wordpress
      args:
        creates: /var/www/html/wordpress/wp-config.php
      when: not ansible_check_mode
      register: wp_config_result

    - name: Install WordPress
      command: wp core install
      args:
        chdir: /var/www/html/wordpress
      when: not ansible_check_mode and wp_config_result.rc == 0
